/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package geneziotestclient

import java.awt.Color
import java.awt.image.BufferedImage
import java.io.File
import java.io.IOException
import java.nio.charset.StandardCharsets
import java.util.*
import javax.imageio.ImageIO
import kotlin.io.path.Path
import kotlin.io.path.writeBytes

class App {}

fun main(args: Array<String>) {
  val service = sdk.HelloWorldService()

  println(service.getPoints(1,2,5))
}




