name: Install and Test with Yarn

on:
  schedule:
    - cron: "15 0 * * *"
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install Yarn
      run: |
        npm install -g yarn
    - name: Install genezio globally
      run: |
        yarn global add genezio
    - name: Check genezio version with regex major.minor.patch
      run: |
        export PATH="$(yarn global bin):$PATH" & genezio --version | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$'
      
  notify:
    if: always()
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Notify slack success
        if: needs.test.result == 'success'
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel_id: C04QR0X8CQ2
          status: SUCCESS
          color: good
      - name: Notify slack fail
        if: needs.test.result == 'failure'
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel_id: C04QR0X8CQ2
          status: FAILED
          color: danger

